require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  Exclude:
    - 'hanny.gemspec'

Layout/LineLength:
  Max: 140
  IgnoredPatterns: ['(\A|\s)#']

Metrics/ModuleLength:
  Max: 200

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 40

Metrics/AbcSize:
  Max: 60

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ParameterLists:
  Max: 10

Security/MarshalLoad:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/FormatStringToken:
  Enabled: false
